In [2]:
a = [[1,2,3], [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [3]:
b = [[4,4,6], [7, 6, 5]]
b

[[4, 4, 6], [7, 6, 5]]

In [4]:
import numpy as np
a = np.array(a)
b = np.array(b)
c = (a * b).sum(axis=1)
print(c)

d=[0,0]
for i in range(0, 2):
    m=d[i]
    for j in range(0, 3):
        m +=  a[i][j]*b[i][j]
    d[i] = m
print(d)

[30 88]
[30, 88]


In [5]:
e = 2 ** 2 * 3 * c
print(e)

f = [0,0]
for i in range(0, 2):
    f[i] = 2 ** 2 * 3 * d[i]
print(f)

[ 360 1056]
[360, 1056]


In [6]:
f1 = np.array(f)
print(np.shape([1,2,3,4,5,6]))
print(np.shape([[1,2,3],[4,5,6],[7,8,9]]))
if(np.shape([1,2,3,4,5,6]) == (4,)):
    print("OK")

(6,)
(3, 3)


In [7]:
print(a)
print(b)
np.array(a) - np.array(b)

[[1 2 3]
 [4 5 6]]
[[4 4 6]
 [7 6 5]]


array([[-3, -2, -3],
       [-3, -1,  1]])

In [8]:
a = [1,2,3]
b = [4,5,6]
np.array(a) - np.array(b)


array([-3, -3, -3])

In [9]:
np.sqrt(np.sum((np.array(a) - np.array(b))**2))

5.196152422706632

In [10]:
a = np.exp(1j*2)
b = np.exp(2j)
print(a == b)

True


In [11]:
1/2

0.5

In [12]:
3**2*2**5

288

In [13]:
a = np.array((1,2))
print(a)

[1 2]


In [14]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([[4,5,6], [7,8,9]])
if(len(a) == len(b)):
    print("OK")

OK


In [15]:
A = np.zeros((3, 4),dtype=complex)
print(A)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [16]:
pi = np.pi
print(pi)

3.141592653589793


In [18]:
a = [1,2,3]
b = [4,5,6]
diff = np.array(a) - np.array(b)
print(diff)

[-3 -3 -3]


In [20]:
diff_x = diff[0]
diff_y = diff[1]
diff_z = diff[2]
print(diff_x, diff_y, diff_z)

-3 -3 -3


In [21]:
diff[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [24]:
def myadd(a, b):
    "testing"
    return a + b

print(myadd(1, 3))

4


In [27]:
def aisle(a, b, c):
    return a, b, c

print(aisle(1,'str',[1,2,3]))

(1, 'str', [1, 2, 3])


In [28]:
np.zeros((10, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])