In [50]:
a = [[1,2,3], [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [51]:
b = [[4,4,6], [7, 6, 5]]
b

[[4, 4, 6], [7, 6, 5]]

In [62]:
import numpy as np
a = np.array(a)
b = np.array(b)
c = (a * b).sum(axis=1)
print(c)

d=[0,0]
for i in range(0, 2):
    m=d[i]
    for j in range(0, 3):
        m +=  a[i][j]*b[i][j]
    d[i] = m
print(d)

[30 88]
[30, 88]
[ 360 1056]


In [64]:
e = 2 ** 2 * 3 * c
print(e)

f = [0,0]
for i in range(0, 2):
    f[i] = 2 ** 2 * 3 * d[i]
print(f)

[ 360 1056]
[360, 1056]


In [104]:
f1 = np.array(f)
print(np.shape([1,2,3,4,5,6]))
print(np.shape([[1,2,3],[4,5,6],[7,8,9]]))
if(np.shape([1,2,3,4,5,6]) == (4,)):
    print("OK")

(6,)
(3, 3)


In [66]:
print(a)
print(b)
np.array(a) - np.array(b)

[[1 2 3]
 [4 5 6]]
[[4 4 6]
 [7 6 5]]


array([[-3, -2, -3],
       [-3, -1,  1]])

In [72]:
a = [1,2,3]
b = [4,5,6]
np.array(a) - np.array(b)


array([-3, -3, -3])

In [83]:
np.sqrt(np.sum((np.array(a) - np.array(b))**2))

5.196152422706632

In [118]:
a = np.exp(1j*2)
b = np.exp(2j)
print(a == b)

True


In [119]:
1/2

0.5

In [121]:
3**2*2**5

288